# Generated by Django 5.0.6 on 2024-09-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_alter_chat_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default='<function now at 0x104491620>'),
        ),
    ]
